// auth actions

export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';

// agency actions

export const FETCH_AGENCY_INFO = 'FETCH_AGENCY_INFO';
export const FETCH_AGENCY_CLIENTS = 'FETCH_AGENCY_CLIENTS';
export const CREATE_NEW_CLIENT = 'CREATE_NEW_CLIENT';
export const FETCH_ALL_CLIENTS = 'FETCH_ALL_CLIENTS';